
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'km';

// --- TRANSLATION DICTIONARY ---
const translations = {
  en: {
    // General
    dashboard: "Dashboard",
    Dashboard: "Dashboard",
    // New Title Case Keys
    Analytics: "Analytics",
    Journal: "General Journal",
    Banking: "Banking & Cash",
    "Staff Loans": "Staff Loans",
    Closing: "Period Closing",
    Booking: "Booking",
    "Parcel List": "Parcel Bookings",
    Operations: "Operations",
    Dispatch: "Dispatch",
    Warehouse: "Warehouse",
    Fleet: "Fleet",
    Places: "Places & Zones",
    Commissions: "Commissions",
    "Logistics Config": "Logistics Configuration",
    Reports: "Reports",
    "Aging Report": "Aging Report",
    Retention: "Retention",
    Configuration: "Configuration",
    Users: "Users",
    Manual: "User Manual",
    "My Deliveries": "My Deliveries",
    "Pickup Jobs": "Pickup Jobs",
    "My Earnings": "My Earnings",
    "My Wallet": "My Wallet",
    "New Booking": "New Booking",
    "My Parcels": "My Parcels",
    Tracking: "Tracking",
    "My Profile": "My Profile",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    actions: "Actions",
    status: "Status",
    date: "Date",
    total: "Total",
    signOut: "Sign Out",
    profile: "Profile",
    search: "Search",
    filter: "Filter",
    print: "Print",
    refresh: "Refresh",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    reset: "Reset",
    remove: "Remove",

    // Statuses
    status_PENDING: "Pending",
    status_CONFIRMED: "Accepted",
    status_PICKED_UP: "Picked Up",
    status_IN_TRANSIT: "In Transit",
    status_AT_WAREHOUSE: "At Warehouse",
    status_DELIVERED: "Delivered",
    status_COMPLETED: "Completed",
    status_CANCELLED: "Cancelled",
    status_RETURN_TO_SENDER: "Returned",
    status_APPROVED: "Approved",
    status_REJECTED: "Rejected",
    status_SETTLED: "Settled",

    // Wallet & Settlement
    wallet: "Wallet",
    my_wallet: "My Wallet",
    net_balance: "Net Balance",
    top_up: "Top Up",
    request_payout: "Request Payout",
    detailed_statement: "Detailed Statement",
    floating_cash: "Floating Cash (To Settle)",
    request_settlement: "Request Settlement",
    settlement_history: "Settlement History",
    proof_of_transfer: "Proof of Transfer",
    submit_request: "Submit Request",
    deposit_to_company: "Deposit To Company",
    pay_to_company: "Pay To Company",
    wallet_credit: "Wallet Credit",
    wallet_debit: "Wallet Debit",
    transaction_type: "Transaction Type",
    pending_approval: "Pending Approval",

    // Admin Sidebar
    analytics: "Analytics",
    journal: "General Journal",
    receivables: "Sales & Receivables",
    payables: "Purchases & Payables",
    banking: "Banking & Cash",
    staff_loans: "Staff Loans",
    fixed_assets: "Fixed Assets",
    parcels: "Parcel Logistics",
    reports: "Financial Reports",
    closing: "Period Closing",
    configuration: "Configuration",
    users: "User Management",
    manual: "User Manual",
    system: "System",

    // Financial Terms
    revenue: "Revenue",
    expenses: "Expenses",
    net_income: "Net Income",
    assets: "Assets",
    liabilities: "Liabilities",
    equity: "Equity",
    recent_activity: "Recent Activity",
    description: "Description",
    reference: "Reference",
    debit: "Debit",
    credit: "Credit",
    balance: "Balance",
    account: "Account",
    code: "Code",
    amount: "Amount",
    currency: "Currency",
    exchange_rate: "Exchange Rate",

    // Reports
    trial_balance: "Trial Balance",
    balance_sheet: "Balance Sheet",
    profit_loss: "Profit & Loss",
    general_ledger: "General Ledger",
    grand_total: "Grand Total",
    from_date: "From Date",
    to_date: "To Date",
    as_of: "As of",

    // Receivables
    invoice: "Invoice",
    customer: "Customer",
    create_invoice: "Create Invoice",
    manage_customers: "Manage Customers",
    aging_report: "Aging Report",
    total_receivables: "Total Receivables",
    overdue_invoices: "Overdue Invoices",
    receive_payment: "Receive Payment",

    // Payables
    bill: "Bill",
    vendor: "Vendor",
    enter_bill: "Enter Bill",
    cash_purchase: "Cash Purchase",
    manage_vendors: "Manage Vendors",
    total_payable: "Total Payable",
    overdue_bills: "Overdue Bills",
    record_payment: "Record Payment",

    // Banking
    transfer_funds: "Transfer Funds",
    add_bank: "Add Bank",
    cash_position: "Cash Position",
    real_time_balance: "Real-time Balance",
    source_account: "Source Account",
    destination_account: "Destination Account",

    // Staff
    employees: "Employees",
    issue_loan: "Issue Loan",
    manage_staff: "Manage Staff",
    settlements: "Settlements",
    accept_deposit: "Accept Deposit",
    total_outstanding: "Total Outstanding",
    total_issued: "Total Issued",
    repay: "Repay",

    // Fixed Assets
    register_asset: "Register Asset",
    depreciation_schedule: "Depreciation Schedule",
    total_asset_cost: "Total Asset Cost",
    net_book_value: "Net Book Value",
    depreciate: "Depreciate",
    dispose: "Dispose",
    purchase_date: "Purchase Date",
    useful_life: "Useful Life",

    // Settings
    general_config: "General",
    chart_of_accounts: "Chart of Accounts",
    branches: "Branches / Warehouses",
    currencies: "Currencies",
    taxes: "Taxes",
    add_account: "Add Account",
    company_name: "Company Name",

    // Parcels / Logistics (Admin)
    overview: "Overview",
    new_booking_admin: "+ New Booking",
    operations: "Operations",
    dispatch: "Dispatch",
    fleet: "Fleet",
    promotions: "Promotions",
    workflow: "Workflow",
    products: "Products",
    parcel_list: "Parcel Bookings",
    sender: "Sender",
    service: "Service",
    items: "Items",
    fee: "Fee",
    warehouse: "Warehouse",
    places: "Places & Zones",
    commissions: "Commissions",
    logistics_config: "Logistics Configuration",
    booking: "Booking",

    // Logistics Booking Form
    step_sender: "Sender & Route",
    step_items: "Parcel Items",
    step_review: "Review & Financials",
    sender_name: "Sender Name",
    sender_phone: "Sender Phone",
    pickup_addr: "Pickup Address",
    est_distance: "Est. Distance (km)",
    delivery_notes: "Delivery Instructions / Notes",
    receiver_name: "Receiver Name",
    receiver_phone: "Receiver Phone",
    dest_addr: "Destination Address",
    item_desc: "Item Description",
    cod_amount: "Cash to Collect (COD)",
    weight: "Weight (kg)",
    tracking_id: "Tracking ID",
    apply_promo: "Apply Promotion",
    booking_status: "Booking Status",
    deposit_to: "Deposit To (If Paid)",
    payment_summary: "Payment Summary",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    total_fee: "Total Fee",
    confirm_booking: "Confirm Booking",
    add_parcel: "+ Add Parcel",

    // Logistics Ops
    search_placeholder: "ID, Sender, Receiver...",
    all_customers: "All Customers",
    all_statuses: "All Statuses",
    showing: "Showing",
    reset_filters: "Reset Filters",
    booking_ref: "Ref",

    // Customer Portal
    my_profile: "My Profile",
    new_booking: "New Booking",
    delivery_reports: "Delivery Reports",
    hello: "Hello",
    track_shipment: "Track your shipments & spend.",
    active_orders: "Active Orders",
    history: "History",
    spent: "Spent",
    new_order: "New Order",

    // Customer Summary Report
    summary_report: "Summary Report",
    financial_overview: "Financial overview of your deliveries.",
    delivery_expenses: "Delivery Expenses",
    total_spent_orders: "Total spent on {0} orders",
    cod_collected: "COD Collected",
    cash_collected_desc: "Cash collected from receivers",
    cod_pending: "COD Pending",
    cod_pending_desc: "In transit or at warehouse",
    transaction_details: "Transaction Details",
    delivery_fee: "Delivery Fee",
    cod_amount_table: "COD Amount",
    no_transactions_period: "No transactions found in this period.",

    // Customer Booking Form
    sender_route: "Sender & Route",
    parcel_details: "Parcel Details",
    financials: "Financials",
    pickup_location: "Pickup Location",
    select_vehicle: "Select Vehicle",
    photo_booking: "Photo Booking",
    manual_entry: "Manual Entry",
    receiver_details: "Receiver Details",
    delivery_instructions: "Delivery Instructions / Note",
    promo_code: "Promo Code",
    review_financials: "Review & Financials",
    cancel_booking: "Cancel Booking",
    confirm_cancel: "Are you sure you want to cancel this booking?",

    // Driver Portal
    my_jobs: "My Jobs",
    pickups: "Pickups",
    active: "Active",
    available: "New",
    settlement: "Settlement",
    cash_on_hand: "Cash On Hand",
    process_pickup: "Process Pickup",
    accept_job: "Accept Job",
    start_delivery: "Start Delivery",
    completed: "Completed",
    failed_return: "Failed / Return",
    confirm_pickup: "Confirm Pickup",

    // Profile & Customer Settings
    saved_locations: "Saved Locations",
    bank_accounts: "Bank Accounts",
    bank_accounts_subtitle: "For Payouts & Settlements",
    referral_program: "Referral Program",
    default_address: "Default Address",
    save_basic_info: "Save Basic Info",
    profile_updated: "Profile updated!",
    need_billing_profile: "You need to set up a billing profile to add bank accounts.",
    init_wallet_profile: "Initialize Wallet Profile",
    bank_name: "Bank Name",
    account_no: "Account No.",
    qr_enabled: "QR Enabled",
    add_bank_account: "Add Bank Account",
    max_bank_limit: "Maximum of 2 bank accounts reached.",
    save_account: "Save Account",
    qr_code_label: "QR Code Image (Optional but Recommended)",
    loc_label_placeholder: "Label (e.g. Home, Office)",
    address_coordinates: "Address / Coordinates",
    enter_address_placeholder: "Enter address or select on map",
    coordinates_set: "Coordinates Set",
    set_primary: "Set Primary",
    primary_badge: "PRIMARY",
    add_new_location: "Add New Location",
    save_location: "Save Location",
    referral_code_title: "Your Unique Referral Code",
    referral_desc: "Share this code with friends. They get a discount, and you get credits!",
    copy_code: "Copy Code",
    copied: "Copied!",
    confirm_delete_location: "Delete this location?",
    confirm_delete_bank: "Delete this bank account?",

    // COD Rate Preference
    cod_pref_title: "COD Exchange Rate Preference",
    daily_rate_title: "Daily Exchange Rate",
    cod_rate_expl: "Set the exchange rate (USD to KHR) that drivers should use when collecting cash for your COD parcels. If you leave this blank, the system default ({0}) will be applied.",
    custom_rate_label: "Your Custom Rate (KHR)",
    update_rate: "Update Rate",
    rate_updated_success: "Exchange rate updated successfully.",
    rate_updated_error: "Failed to update rate.",

    // Auth
    welcome_back: "Welcome back",
    get_started: "Get Started",
    email: "Email address",
    password: "Password",
    login: "Sign In",
    register: "Create Account",
    reset_password: "Reset Password",
    full_name: "Full Name",
    phone_number: "Phone Number",
    forgot_password: "Forgot?",
    create_account: "Create an account",
    sign_in_link: "Sign in",
    i_am_customer: "I'm a Customer",
    business_staff: "Business Staff",
  },
  km: {
    // General
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    Dashboard: "ផ្ទាំងគ្រប់គ្រង",
    // New Title Case Keys (Khmer)
    Analytics: "វិភាគទិន្នន័យ",
    Journal: "កំណត់ត្រាគណនេយ្យ",
    Banking: "ធនាគារ & សាច់ប្រាក់",
    "Staff Loans": "ប្រាក់កម្ចីបុគ្គលិក",
    Closing: "បិទបញ្ជី",
    Booking: "ការកក់",
    "Parcel List": "បញ្ជីបញ្ញើ",
    Operations: "ប្រតិបត្តិការ",
    Dispatch: "ចាត់ចែង",
    Warehouse: "ឃ្លាំង",
    Fleet: "អ្នកដឹកជញ្ជូន",
    Places: "ទីតាំង & តំបន់",
    Commissions: "កម្រៃជើងសារ",
    "Logistics Config": "ការកំណត់ឡូជីស្ទិក",
    Reports: "របាយការណ៍ហិរញ្ញវត្ថុ",
    "Aging Report": "របាយការណ៍បំណុល",
    Retention: "ការរក្សាទុក",
    Configuration: "ការកំណត់ប្រព័ន្ធ",
    Users: "អ្នកប្រើប្រាស់",
    Manual: "សៀវភៅណែនាំ",
    "My Deliveries": "ការដឹកជញ្ជូនរបស់ខ្ញុំ",
    "Pickup Jobs": "ការងារទទួល",
    "My Earnings": "ចំណូលរបស់ខ្ញុំ",
    "My Wallet": "កាបូបលុយខ្ញុំ",
    "New Booking": "ការកក់ថ្មី",
    "My Parcels": "កញ្ចប់របស់ខ្ញុំ",
    Tracking: "ការតាមដាន",
    "My Profile": "ប្រវត្តិរូបខ្ញុំ",
    loading: "កំពុងដំណើរការ...",
    save: "រក្សាទុក",
    cancel: "បោះបង់",
    delete: "លុប",
    edit: "កែប្រែ",
    view: "មើល",
    actions: "សកម្មភាព",
    status: "ស្ថានភាព",
    date: "កាលបរិច្ឆេទ",
    total: "សរុប",
    signOut: "ចាកចេញ",
    profile: "ប្រវត្តិរូប",
    search: "ស្វែងរក",
    filter: "សម្រាំង",
    print: "បោះពុម្ព",
    refresh: "ផ្ទុកឡើងវិញ",
    confirm: "បញ្ជាក់",
    back: "ថយក្រោយ",
    next: "បន្ទាប់",
    reset: "កំណត់ឡើងវិញ",
    remove: "លុបចេញ",

    // Statuses
    status_PENDING: "រង់ចាំ",
    status_CONFIRMED: "បានទទួល",
    status_PICKED_UP: "បានយក",
    status_IN_TRANSIT: "កំពុងដឹក",
    status_AT_WAREHOUSE: "នៅឃ្លាំង",
    status_DELIVERED: "បានដឹក",
    status_COMPLETED: "បានបញ្ចប់",
    status_CANCELLED: "បោះបង់",
    status_RETURN_TO_SENDER: "ត្រឡប់វិញ",
    status_APPROVED: "អនុម័ត",
    status_REJECTED: "បដិសេធ",
    status_SETTLED: "ទូទាត់ហើយ",

    // Wallet & Settlement
    wallet: "កាបូបលុយ",
    my_wallet: "កាបូបលុយខ្ញុំ",
    net_balance: "សមតុល្យសុទ្ធ",
    top_up: "បញ្ចូលលុយ",
    request_payout: "ស្នើសុំដកប្រាក់",
    detailed_statement: "របាយការណ៍លម្អិត",
    floating_cash: "សាច់ប្រាក់ក្នុងដៃ (ត្រូវទូទាត់)",
    request_settlement: "ស្នើសុំទូទាត់",
    settlement_history: "ប្រវត្តិទូទាត់",
    proof_of_transfer: "វិក្កយបត្រវេរលុយ (បោះពុម្ព)",
    submit_request: "ដាក់ស្នើ",
    deposit_to_company: "ដាក់ប្រាក់ចូលក្រុមហ៊ុន",
    pay_to_company: "បង់ប្រាក់ទៅក្រុមហ៊ុន",
    wallet_credit: "ឥណទានកាបូប",
    wallet_debit: "ឥណពន្ធកាបូប",
    transaction_type: "ប្រភេទប្រតិបត្តិការ",
    pending_approval: "រង់ចាំការអនុម័ត",

    // Admin Sidebar
    analytics: "វិភាគទិន្នន័យ",
    journal: "កំណត់ត្រាគណនេយ្យ",
    receivables: "ការលក់ & ចំណូល",
    payables: "ការទិញ & ចំណាយ",
    banking: "ធនាគារ & សាច់ប្រាក់",
    staff_loans: "ប្រាក់កម្ចីបុគ្គលិក",
    fixed_assets: "ទ្រព្យសកម្ម",
    parcels: "សេវាដឹកជញ្ជូន",
    reports: "របាយការណ៍ហិរញ្ញវត្ថុ",
    closing: "បិទបញ្ជី",
    configuration: "ការកំណត់ប្រព័ន្ធ",
    users: "អ្នកប្រើប្រាស់",
    manual: "សៀវភៅណែនាំ",
    system: "ប្រព័ន្ធ",

    // Financial Terms
    revenue: "ចំណូល",
    expenses: "ចំណាយ",
    net_income: "ប្រាក់ចំណេញសុទ្ធ",
    assets: "ទ្រព្យសកម្ម",
    liabilities: "បំណុល",
    equity: "មូលធន",
    recent_activity: "សកម្មភាពថ្មីៗ",
    description: "ការពិពណ៌នា",
    reference: "យោង",
    debit: "ឥណពន្ធ (Debit)",
    credit: "ឥណទាន (Credit)",
    balance: "សមតុល្យ",
    account: "គណនី",
    code: "កូដ",
    amount: "ចំនួនទឹកប្រាក់",
    currency: "រូបិយប័ណ្ណ",
    exchange_rate: "អត្រាប្តូរប្រាក់",

    // Reports
    trial_balance: "តារាងតុល្យការ",
    balance_sheet: "តារាងតុល្យការ (BS)",
    profit_loss: "របាយការណ៍ចំណូលចំណាយ",
    general_ledger: "សៀវភៅធំ",
    grand_total: "សរុបរួម",
    from_date: "ចាប់ពីថ្ងៃ",
    to_date: "ដល់ថ្ងៃ",
    as_of: "គិតត្រឹម",

    // Receivables
    invoice: "វិក្កយបត្រ",
    customer: "អតិថិជន",
    create_invoice: "បង្កើតវិក្កយបត្រ",
    manage_customers: "គ្រប់គ្រងអតិថិជន",
    aging_report: "របាយការណ៍បំណុល",
    total_receivables: "ចំណូលត្រូវទទួលសរុប",
    overdue_invoices: "វិក្កយបត្រហួសកាលកំណត់",
    receive_payment: "ទទួលប្រាក់",

    // Payables
    bill: "វិក្កយបត្រចំណាយ",
    vendor: "អ្នកផ្គត់ផ្គង់",
    enter_bill: "បញ្ចូលវិក្កយបត្រ",
    cash_purchase: "ទិញសាច់ប្រាក់",
    manage_vendors: "គ្រប់គ្រងអ្នកផ្គត់ផ្គង់",
    total_payable: "បំណុលត្រូវសងសរុប",
    overdue_bills: "វិក្កយបត្រហួសកាលកំណត់",
    record_payment: "កត់ត្រាការទូទាត់",

    // Banking
    transfer_funds: "ផ្ទេរប្រាក់",
    add_bank: "បន្ថែមធនាគារ",
    cash_position: "ស្ថានភាពសាច់ប្រាក់",
    real_time_balance: "សមតុល្យជាក់ស្តែង",
    source_account: "គណនីដើម",
    destination_account: "គណនីគោលដៅ",

    // Staff
    employees: "បុគ្គលិក",
    issue_loan: "ផ្តល់កម្ចី",
    manage_staff: "គ្រប់គ្រងបុគ្គលិក",
    settlements: "ទូទាត់ប្រាក់",
    accept_deposit: "ទទួលប្រាក់កក់",
    total_outstanding: "កម្ចីសរុបនៅសល់",
    total_issued: "កម្ចីសរុបបានផ្តល់",
    repay: "សងប្រាក់",

    // Fixed Assets
    register_asset: "ចុះបញ្ជីទ្រព្យ",
    depreciation_schedule: "តារាងរំលស់",
    total_asset_cost: "ថ្លៃដើមទ្រព្យសរុប",
    net_book_value: "តម្លៃសៀវភៅសុទ្ធ",
    depreciate: "គិតរំលស់",
    dispose: "លុបចោល/លក់",
    purchase_date: "កាលបរិច្ឆេទទិញ",
    useful_life: "អាយុកាលប្រើប្រាស់",

    // Settings
    general_config: "ទូទៅ",
    chart_of_accounts: "តារាងគណនី",
    branches: "សាខា / ឃ្លាំង",
    currencies: "រូបិយប័ណ្ណ",
    taxes: "ពន្ធ",
    add_account: "បន្ថែមគណនី",
    company_name: "ឈ្មោះក្រុមហ៊ុន",

    // Parcels / Logistics (Admin)
    overview: "ទិដ្ឋភាពទូទៅ",
    new_booking_admin: "+ ការកក់ថ្មី",
    operations: "ប្រតិបត្តិការ",
    dispatch: "ចាត់ចែង",
    fleet: "អ្នកដឹកជញ្ជូន",
    promotions: "ប្រូម៉ូសិន",
    workflow: "លំហូរការងារ",
    products: "ផលិតផល/សេវា",
    parcel_list: "បញ្ជីបញ្ញើ",
    sender: "អ្នកផ្ញើ",
    service: "សេវាកម្ម",
    items: "ទំនិញ",
    fee: "ថ្លៃសេវា",
    warehouse: "ឃ្លាំង",
    places: "ទីតាំង & តំបន់",
    commissions: "កម្រៃជើងសារ",
    logistics_config: "ការកំណត់ឡូជីស្ទិក",
    booking: "ការកក់",
    retention: "ការរក្សាទុក",
    tracking: "ការតាមដាន",
    my_deliveries: "ការដឹកជញ្ជូនរបស់ខ្ញុំ",
    pickup_jobs: "ការងារទទួល",
    my_earnings: "ចំណូលរបស់ខ្ញុំ",
    my_parcels: "កញ្ចប់របស់ខ្ញុំ",

    // Logistics Booking Form
    step_sender: "អ្នកផ្ញើ & ផ្លូវ",
    step_items: "ទំនិញបញ្ញើ",
    step_review: "ពិនិត្យ & ហិរញ្ញវត្ថុ",
    sender_name: "ឈ្មោះអ្នកផ្ញើ",
    sender_phone: "លេខទូរស័ព្ទអ្នកផ្ញើ",
    pickup_addr: "អាសយដ្ឋានទទួល (Pickup)",
    est_distance: "ចម្ងាយប្រហែល (km)",
    delivery_notes: "កំណត់សម្គាល់ / ណែនាំ",
    receiver_name: "ឈ្មោះអ្នកទទួល",
    receiver_phone: "លេខទូរស័ព្ទអ្នកទទួល",
    dest_addr: "អាសយដ្ឋានគោលដៅ",
    item_desc: "បរិយាយទំនិញ",
    cod_amount: "សាច់ប្រាក់ត្រូវប្រមូល (COD)",
    weight: "ទម្ងន់ (kg)",
    tracking_id: "លេខកូដតាមដាន (Tracking ID)",
    apply_promo: "ប្រើប្រូម៉ូសិន",
    booking_status: "ស្ថានភាពការកក់",
    deposit_to: "ដាក់ប្រាក់ទៅ (បើបានបង់)",
    payment_summary: "សង្ខេបការទូទាត់",
    subtotal: "សរុបរង",
    discount: "បញ្ចុះតម្លៃ",
    tax: "ពន្ធ",
    total_fee: "ថ្លៃសេវាសរុប",
    confirm_booking: "បញ្ជាក់ការកក់",
    add_parcel: "+ បន្ថែមទំនិញ",

    // Logistics Ops
    search_placeholder: "លេខកូដ, អ្នកផ្ញើ, អ្នកទទួល...",
    all_customers: "អតិថិជនទាំងអស់",
    all_statuses: "ស្ថានភាពទាំងអស់",
    showing: "បង្ហាញ",
    reset_filters: "កំណត់សម្រាំងឡើងវិញ",
    booking_ref: "យោង",

    // Customer Portal
    my_profile: "ប្រវត្តិរូបខ្ញុំ",
    new_booking: "ការកក់ថ្មី",
    delivery_reports: "របាយការណ៍ដឹកជញ្ជូន",
    hello: "សួស្តី",
    track_shipment: "តាមដានការដឹកជញ្ជូន និងការចំណាយរបស់អ្នក",
    active_orders: "ការកក់សកម្ម",
    history: "ប្រវត្តិ",
    spent: "បានចំណាយ",
    new_order: "ការកក់ថ្មី",

    // Customer Summary Report
    summary_report: "របាយការណ៍សង្ខេប",
    financial_overview: "ទិដ្ឋភាពទូទៅហិរញ្ញវត្ថុនៃការដឹកជញ្ជូនរបស់អ្នក។",
    delivery_expenses: "ចំណាយដឹកជញ្ជូន",
    total_spent_orders: "ចំណាយសរុបលើការកក់ចំនួន {0}",
    cod_collected: "COD បានប្រមូល",
    cash_collected_desc: "សាច់ប្រាក់បានប្រមូលពីអ្នកទទួល",
    cod_pending: "COD រង់ចាំ",
    cod_pending_desc: "កំពុងដឹក ឬនៅឃ្លាំង",
    transaction_details: "ព័ត៌មានលម្អិតប្រតិបត្តិការ",
    delivery_fee: "ថ្លៃដឹក",
    cod_amount_table: "ចំនួន COD",
    no_transactions_period: "រកមិនឃើញប្រតិបត្តិការនៅក្នុងអំឡុងពេលនេះទេ។",

    // Customer Booking Form
    sender_route: "អ្នកផ្ញើ & ផ្លូវ",
    parcel_details: "ព័ត៌មានលម្អិតអំពីកញ្ចប់",
    financials: "ហិរញ្ញវត្ថុ",
    pickup_location: "ទីតាំងទទួល",
    select_vehicle: "ជ្រើសរើសយានជំនិះ",
    photo_booking: "កក់តាមរូបថត",
    manual_entry: "បញ្ចូលដោយដៃ",
    receiver_details: "ព័ត៌មានអ្នកទទួល",
    delivery_instructions: "ណែនាំការដឹកជញ្ជូន",
    promo_code: "លេខកូដប្រូម៉ូសិន",
    review_financials: "ពិនិត្យ & ហិរញ្ញវត្ថុ",
    cancel_booking: "បោះបង់ការកក់",
    confirm_cancel: "តើអ្នកប្រាកដថាចង់បោះបង់ការកក់នេះទេ?",

    // Driver Portal
    my_jobs: "ការងារខ្ញុំ",
    pickups: "ការទទួល",
    active: "សកម្ម",
    available: "ថ្មី",
    settlement: "ការទូទាត់",
    cash_on_hand: "សាច់ប្រាក់ក្នុងដៃ",
    process_pickup: "ដំណើរការទទួល",
    accept_job: "ទទួលការងារ",
    start_delivery: "ចាប់ផ្តើមដឹក",
    completed: "បានបញ្ចប់",
    failed_return: "បរាជ័យ / ត្រឡប់",
    confirm_pickup: "បញ្ជាក់ការទទួល",

    // Profile & Customer Settings
    saved_locations: "ទីតាំងដែលបានរក្សាទុក",
    bank_accounts: "គណនីធនាគារ",
    bank_accounts_subtitle: "សម្រាប់ការទូទាត់ & ដកប្រាក់",
    referral_program: "កម្មវិធីណែនាំ",
    default_address: "អាសយដ្ឋានលំនាំដើម",
    save_basic_info: "រក្សាទុកព័ត៌មាន",
    profile_updated: "ប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាព!",
    need_billing_profile: "អ្នកត្រូវបង្កើតប្រវត្តិរូបកាបូបលុយ ដើម្បីបន្ថែមគណនីធនាគារ។",
    init_wallet_profile: "បង្កើតប្រវត្តិរូបកាបូបលុយ",
    bank_name: "ឈ្មោះធនាគារ",
    account_no: "លេខគណនី",
    qr_enabled: "មាន QR",
    add_bank_account: "បន្ថែមគណនីធនាគារ",
    max_bank_limit: "បានដល់កំណត់គណនីធនាគារចំនួន ២ ហើយ។",
    save_account: "រក្សាទុកគណនី",
    qr_code_label: "រូបភាព QR Code (ស្រេចចិត្ត ប៉ុន្តែណែនាំ)",
    loc_label_placeholder: "ស្លាក (ឧ. ផ្ទះ, ការិយាល័យ)",
    address_coordinates: "អាសយដ្ឋាន / កូអរដោនេ",
    enter_address_placeholder: "បញ្ចូលអាសយដ្ឋាន ឬជ្រើសរើសលើផែនទី",
    coordinates_set: "កូអរដោនេត្រូវបានកំណត់",
    set_primary: "កំណត់ជាចម្បង",
    primary_badge: "ចម្បង",
    add_new_location: "បន្ថែមទីតាំងថ្មី",
    save_location: "រក្សាទុកទីតាំង",
    referral_code_title: "លេខកូដណែនាំរបស់អ្នក",
    referral_desc: "ចែករំលែកលេខកូដនេះជាមួយមិត្តភក្តិ។ ពួកគេទទួលបានការបញ្ចុះតម្លៃ ហើយអ្នកទទួលបានឥណទាន!",
    copy_code: "ចម្លងកូដ",
    copied: "បានចម្លង!",
    confirm_delete_location: "លុបទីតាំងនេះឬ?",
    confirm_delete_bank: "លុបគណនីធនាគារនេះឬ?",

    // COD Rate Preference
    cod_pref_title: "ការកំណត់អត្រាប្តូរប្រាក់ COD",
    daily_rate_title: "អត្រាប្តូរប្រាក់ប្រចាំថ្ងៃ",
    cod_rate_expl: "កំណត់អត្រាប្តូរប្រាក់ (ដុល្លារ ទៅ រៀល) ដែលអ្នកដឹកជញ្ជូនប្រើពេលប្រមូលប្រាក់ COD។ ប្រសិនបើទុកចោល ប្រព័ន្ធនឹងប្រើអត្រាលំនាំដើម ({0})។",
    custom_rate_label: "អត្រាផ្ទាល់ខ្លួន (រៀល)",
    update_rate: "កែប្រែអត្រា",
    rate_updated_success: "អត្រាប្តូរប្រាក់ត្រូវបានកែប្រែដោយជោគជ័យ។",
    rate_updated_error: "បរាជ័យក្នុងការកែប្រែអត្រា។",

    // Auth
    welcome_back: "សូមស្វាគមន៍",
    get_started: "ចាប់ផ្តើម",
    email: "អាសយដ្ឋានអ៊ីមែល",
    password: "ពាក្យសម្ងាត់",
    login: "ចូលប្រើ",
    register: "បង្កើតគណនី",
    reset_password: "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
    full_name: "ឈ្មោះ​ពេញ",
    phone_number: "លេខទូរស័ព្ទ",
    forgot_password: "ភ្លេចពាក្យសម្ងាត់?",
    create_account: "បង្កើតគណនី",
    sign_in_link: "ចូលប្រើ",
    i_am_customer: "ខ្ញុំជាអតិថិជន",
    business_staff: "បុគ្គលិកក្រុមហ៊ុន",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'km')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
